# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
