# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 12:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170811_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/mnt/d/code/blogs/static/thumb'), upload_to=''),
        ),
    ]
